# Generated by Django 3.0.5 on 2020-05-29 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='content',
            new_name='body',
        ),
    ]
