# Generated by Django 3.0.5 on 2020-06-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_twitteruser_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowModel',
        ),
    ]
